### PR TITLE
Delete and edit comments 

### LINKED ISSUE #1312: Edit/Delete comments
I'd like to open this issue as a feature request to add the ability to edit and/or delete comments made on events.

### PR DESCRIPTION
**Pull request by hkhalifa**
+ What existing problem does this PR solve?
   Users are not able to delete or edit existing comments on events
+ What new feature is being introduced with this PR?
   Adds the ability to delete or edit existing comments
+ Overview of changes to existing functions if required.

**Closing issues**

closes #1312

00324a8e-c0dc-49d9-9498-e40db0a1f9d3

### CODE REVIEW

**Review by berggren — CHANGES_REQUESTED** [review]
First round done - looks good. See my comments and let me know when you are ready for a second round.

**Review by jaegeral — COMMENTED** [review]
Would you mind to also write a short blob around the additions to the API and the UI for https://github.com/google/timesketch/tree/master/docs?

Other then that, would the code be ready for another round of reviews?

**Comment by hkhalifa** [comment]
Sure, I will add something in https://github.com/google/timesketch/tree/master/docs 

And yes, it's ready for review.

**Review by berggren — APPROVED** [review]
LGTM (sorry for the delay)

**Pull request merged**
