### PR TITLE
Bump sigmatools pypi version up

### PR DESCRIPTION
**Pull request by jaegeral**

### CODE REVIEW

**Review by kiddinn — APPROVED** [review]
LGTM

**Comment by jaegeral** [comment]
Ok this is not be ready to be merged, because it is blocked by: https://github.com/Neo23x0/sigma/issues/1180 @Neo23x0.

**Review by berggren — CHANGES_REQUESTED** [review]
Let's wait with this until after the release

**Comment by berggren** [comment]
@kiddinn do mot merge this one just yet.

**Comment by joachimmetz** [comment]
FYI upstream is still broken

**Comment by joachimmetz** [comment]
Upstream issue has been resolved in 0.19.1 please use that version

**Comment by berggren** [comment]
@jaegeral Can you update the packaking conf as well: https://github.com/google/timesketch/blob/da936fafe36dd0d950bfe34af235f3bd5441f87c/dependencies.ini#L273

**Comment by jaegeral** [comment]
> @jaegeral Can you update the packaking conf as well:
> 
> https://github.com/google/timesketch/blob/da936fafe36dd0d950bfe34af235f3bd5441f87c/dependencies.ini#L273

Yep, set it to 0.19.1 also in the requirements file

**Review by berggren — APPROVED** [review]

**Pull request merged**
