### PR TITLE
Update timesketch_importer.py

### PR DESCRIPTION
**Pull request by jaegeral**
Fixes https://github.com/google/timesketch/issues/1872

### CODE REVIEW

**Review by kiddinn — COMMENTED** [review]
Why not have both the description and the status?

**Comment by jaegeral** [comment]
> Why not have both the description and the status?

That is certainly also an option, I was not sure if the timeline name here was just a copy paste error, because with the lack of status it was very hard to tell why it failed so I made it the status, but happy to at the description as well.

**Review by kiddinn — APPROVED** [review]
LGTM

but please send another PR in to upgrade the version number, so that a new build can be pushed

**Comment by berggren** [comment]
@jaegeral Can you update the version number in this PR (version.py) so we can push a new release as well? After that this is good to merge.

**Comment by jaegeral** [comment]
> @jaegeral Can you update the version number in this PR (version.py) so we can push a new release as well? After that this is good to merge.

Sure that, done

**Pull request merged**
