### PR TITLE
Dark Mode

### PR DESCRIPTION
**Pull request by berggren**
This PR adds a Dark Mode theme. It uses CSS variables and element data selector to switch between light and dark.

* Loosely based on Material Design dark mode principles.
* Tone down timeline colors and button colors, using gray filter of 25%
* Uses localStorage to make the setting sticky per device.

Screenshot 2020-09-21 at 19 50 51

This is just the first take on this. Known issues:
* Vega charts don't look good on dark background. Will be fixed on an upcoming PR.
* Some elements might be difficult to see because contrast is too low. Will open bugs and fix as they are identified.

Fixes: #1373

### CODE REVIEW

**Comment by kiddinn** [comment]
tests are failing.... travis complaints since:

```
ModuleNotFoundError: No module named 'vine.five'

```

**Review by kiddinn — CHANGES_REQUESTED** [review]
can you fix the issue with the missing module? otherwise LGTM

**Comment by berggren** [comment]
Will fix the missing GIFT package in another PR.

**Review by kiddinn — APPROVED** [review]
LGTM

**Comment by joachimmetz** [comment]
Related https://github.com/log2timeline/l2tdevtools/issues/904

**Pull request merged**
