### PR TITLE
Issue 1887 timefilters bug

### LINKED ISSUE #1887: UI: Time filter doesn't parse time correctly
**Describe the bug**
When I add a time filter that is missing seconds, e.g. "2021-01-01 11:22" and then go to update it, then the time part (i.e. "11:22") is missing.

**To Reproduce**
1. Go to 'Explore'
2. Click on '+ Time filter'
3. Enter '2021-01-01 11:22' and press the "Add filter" button
4. Click the button to update the time filter that was just created

**Expected behavior**
The text box should show "2021-01-01 11:22" or "2021-01-01 11:22:00".

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Chromebook
 - Browser: Chrome
 - Version: 91

### PR DESCRIPTION
**Pull request by binglot**
Closes #1887

### CODE REVIEW

**Comment by binglot** [comment]
For some reason the PR also contains 2 other files that I didn't create as part of the changes. I'll need to fix that before it can be merged.

**Comment by binglot** [comment]
Fixed

**Review by berggren — APPROVED** [review]

**Review by berggren — CHANGES_REQUESTED** [review]
Looks good, but please fix the linter error:
```
/home/runner/work/timesketch/timesketch/timesketch/frontend/src/components/Explore/TimeFilter.vue
  180:49  error  Unnecessary escape character: \/  no-useless-escape
  ```

**Comment by binglot** [comment]
> Looks good, but please fix the linter error:
> 
> ```
> /home/runner/work/timesketch/timesketch/timesketch/frontend/src/components/Explore/TimeFilter.vue
>   180:49  error  Unnecessary escape character: \/  no-useless-escape
> ```

I missed the linter error, thanks for pointing this out! :) This is so weird though, because when I test the regex on Rubular without the escape then it doesn't work.

**Review by berggren — APPROVED** [review]

**Pull request merged**
