### PR TITLE
Fix Docker installation documentation link.

### PR DESCRIPTION
**Pull request by hacktobeer**

### CODE REVIEW

**Comment by hacktobeer** [comment]
@googlebot I signed it!

**Comment by hacktobeer** [comment]
Discard pull request, need to reset my git user/email as it's still set to my former employment.

**Comment by MrNonoss** [comment]
Hi there, 
I think this issue should be reopened since the documentation that refers to install with docker does no longuer work. There seems to be no doc anymore on that.
Is it a work in progress?

**Comment by hacktobeer** [comment]
You are correct, let me fix that.
You can find the README at https://github.com/google/timesketch/blob/master/docker/dev/README.md

**Comment by MrNonoss** [comment]
Thanks à lot.
Yeah I was able to find it on the table branch 👍

**Pull request closed without merging**
