### PR TITLE
Added dockerfile build CI tests

### PR DESCRIPTION
**Pull request by joachimmetz**
* Moved docker to config/docker
* Added Dockerfile Travis-CI test

### CODE REVIEW

**Comment by joachimmetz** [comment]
@berggren the dockerfile build is failing with `error Couldn't find a package.json file in "/tmp/timesketch"` any idea what could be causing this?

**Comment by berggren** [comment]
This looks good, one question: why move the docker dir? It is common to host it at the root level and is what many people expect. Can you move it back and I'll merge? :)

**Comment by joachimmetz** [comment]
> It is common to host it at the root level and is what many people expect

It clutters the source tree, and since it was a configuration, config looked a more appropriate place to me. I also moved it there to maybe standardize on generation of test scripts.

**Comment by joachimmetz** [comment]
@berggren updated

**Comment by berggren** [comment]
@joachimmetz excellent. I'll take a look at the package.json issue before merge. I let you know.

**Comment by jaegeral** [comment]
@berggren seems there are some conflicts that block the merge here

**Comment by berggren** [comment]
Closing this PR, as it has been replaces since with a bigger overhaul of Docker for TS.

**Comment by joachimmetz** [comment]
ack as discussed will likely reintroduce docker build tests after updating the deps and test scripts.

**Pull request closed without merging**
