### PR TITLE
Implicit String Fix

### LINKED ISSUE #2611: Implicit Operation on Strings
Greetings,

While going through the code, I found this issue.

**Describe the bug**
Confusion in tuple where string are being concatenated implicitly 

**To Reproduce**
1. Go to `lib/aggregators/term.py`
2. Navigate to line `102`

**Expected behavior**
1. Should be a tuple split by a comma or should be a single string.

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [NA]
 - Version [NA]

**Additional context**
NA

### PR DESCRIPTION
**Pull request by LX5321**
Fixed strings and removed spaces.

Closes #2611

### CODE REVIEW

**Comment by jaegeral** [comment]
@LX5321 could you sign the CLA? Then we can move forward.

Thank you

**Comment by LX5321** [comment]
@jaegeral Sure, will close this PR and make a fresh one for the same.

**Comment by jaegeral** [comment]
No you just need to sign it and then it will tell you how to re-check

**Comment by LX5321** [comment]
Ah that worked, thanks!

**Comment by venkatesh799** [comment]
if this issue not merged can i work on it ?

**Review by berggren — APPROVED** [review]
LGTM, thanks for fixing this, and sorry for the delay.

**Pull request merged**
