### PR TITLE
Improve aggregation view

### LINKED ISSUE #2053: UI aggregate - altair limit to 5000 return events
When you use aggregate UI, you can choose the "Number of results to return", if you choose number > 5000 then make error:

```
[2021-11-29 08:09:21,888] timesketch.app/ERROR Exception on /api/v1/sketches/2/aggregation/explore/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/aggregation.py", line 532, in post
    meta['vega_spec'] = result_obj.to_chart(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/aggregators/interface.py", line 131, in to_chart
    return chart.to_dict()
  File "/usr/local/lib/python3.8/dist-packages/altair/vegalite/v4/api.py", line 363, in to_dict
    copy.data = _prepare_data(original_data, context)
  File "/usr/local/lib/python3.8/dist-packages/altair/vegalite/v4/api.py", line 84, in _prepare_data
    data = _pipe(data, data_transformers.get())
  File "/usr/local/lib/python3.8/dist-packages/toolz/functoolz.py", line 630, in pipe
    data = func(data)
  File "/usr/local/lib/python3.8/dist-packages/toolz/functoolz.py", line 306, in __call__
    return self._partial(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/altair/vegalite/data.py", line 19, in default_data_transformer
    return curried.pipe(data, limit_rows(max_rows=max_rows), to_values)
  File "/usr/local/lib/python3.8/dist-packages/toolz/functoolz.py", line 630, in pipe
    data = func(data)
  File "/usr/local/lib/python3.8/dist-packages/toolz/functoolz.py", line 306, in __call__
    return self._partial(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/altair/utils/data.py", line 80, in limit_rows
    raise MaxRowsError(
altair.utils.data.MaxRowsError: The number of rows in your dataset is greater than the maximum allowed (5000). For information on how to plot larger datasets in Altair, see the documentation
```
You can disable this error by disable: "alt.data_transformers.disable_max_rows()"
Ref: https://altair-viz.github.io/user_guide/faq.html#disabling-maxrowserror

Can you tell me if max value is a desire of your team ? If yes, can you add option in config to disable this error ?

Thank.
Lionel

### LINKED ISSUE #2076: Aggregation view improve
**Is your feature request related to a problem? Please describe.**
I would like to choose in term "table" result:
  - number of result to display by page
  - possible to filter term by regexp
  - order term aggregation by ASC or DESC from elastic

image

On filtered aggregation 'table", I would like:
  - to pre filter result from regexp to keep only group (from regexp)
    - exemple:  message contains several information including FS PATH, and you want just get FS PATH information (without use FEATURE analyzer):
image

  - To get information on first, last date to exist this term and duration between first and last event:
image

**Describe the solution you'd like**
PR.

**Describe alternatives you've considered**

**Additional context**
image
image
image

### PR DESCRIPTION
**Pull request by lprat**
PR to Issue #2076 and #2053

Fix #2053

Add feature to aggregation view:
  - Choose number of result to display (today fixed to 10)
  - Get order from elastic aggregation (DESC or ASC)
  - Filter result term by regexp 
  - Pre filter by regexp group elastic term result
  - Get information of first and last date of event for each term and duration between first and last event.

**Checks**

- [ ] All tests succeed.
- [ ] Unit tests added.
- [ ] e2e tests added.
- [ ] Documentation updated.

**Closing issues**

Put `closes #2053` in your comment to auto-close the issue that your PR fixes
(if such).
Put `closes #2076` in your comment to auto-close the issue that your PR fixes
(if such).

### CODE REVIEW

**Comment by berggren** [comment]
Hey @lprat - I'll take a look at this PR as soon as possible. In the meantime please take a look at the linter errors.

**Comment by lprat** [comment]
I fixed conflit on interface.py & term.py

**Comment by berggren** [comment]
Hi again, can you also post a few screenshots with the changes?
There are conflicts, can you take a look?

Sorry for the delay here, but I'll take a closer look at the code as soon as time permits.

**Comment by lprat** [comment]
Hi, the screenshots are in issue: https://github.com/google/timesketch/issues/2076 .
I look quickly for conflit.
Thank

**Comment by lprat** [comment]
image
image
image

**Comment by lprat** [comment]
@berggren @jaegeral  I fixed formatting. Please let me know if it's ok for you.
Thanks

**Comment by lprat** [comment]
@berggren @jaegeral I wait for your review. Thanks

**Comment by jaegeral** [comment]
We have not yet ported it over, but it is def something we want to double down and make the user experience better and more useful

**Comment by berggren** [comment]
> Hi @jaegeral & @berggren ,
> 
> A question about frontend-NG v2 (#2193) , you dont keep "aggregation view" ?
> 
> Thx

We are planning to port the aggregations over in the near future. We are rethinking the whole UI for it.

**Comment by berggren** [comment]
Hi @lprat sorry for the (very) long delay on this PR. The old UI that this PR is on is deprecated in favour of a new, refreshed UI using material design. We will not be merging any new features to the old UI.

I will setup a chat with you to discuss future contributions, and how to align. Looking forward to hearing about our ideas.

**Pull request closed without merging**
