### PR TITLE
Update deploy_timesketch.sh - add ontology.yaml

### LINKED ISSUE #2031: Error when adding intelligence: Value needs to be a string
**Describe the bug**
When adding a value ('other', 'hostname') as intelligence I get the error message "Internal Server Error" in the Timesketch UI.

**To Reproduce**
1. Open sketch, select timeline
2. Select a string, fe 'MYCP'
3. Select 'other', 'Add' (the error occurs for every type of intelligence)

**Expected behavior**
Adding intelligence without an error

**Desktop (please complete the following information):**
 - OS: Ubuntu 20
 - Version: Latest Docker versions (installed according to https://github.com/google/timesketch/blob/master/docs/guides/admin/install.md )

**Additional context**

The output from /**var/log/timesketch/wsgi_error.log** in the Docker container **us-docker.pkg.dev/osdfir-registry/timesketch/timesketch:latest** returned this error
```
[2021-11-13 20:41:36,070] timesketch.app/ERROR Exception on /api/v1/sketches/1/attribute/ [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/attribute.py", line 136, in post
    value_strings = [ontology_lib.OntologyManager.encode_value(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/api/v1/resources/attribute.py", line 136, in <listcomp>
    value_strings = [ontology_lib.OntologyManager.encode_value(
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/ontology.py", line 186, in encode_value
    return cls._types[type_string].encode(value)
  File "/usr/local/lib/python3.8/dist-packages/timesketch/lib/ontology.py", line 61, in encode
    raise ValueError('Value needs to be a string.')
ValueError: Value needs to be a string.
```

### PR DESCRIPTION
**Pull request by cudeso**
**IMPORTANT: All Pull Requests should be connected to an issue, if you don't
have an issue, please start by creating an issue and link it to the PR.**

Closes #2031

**Checks**

- [ ] All tests succeed.
- [ ] Unit tests added.
- [ ] e2e tests added.
- [ ] Documentation updated.

**Closing issues**

Put `closes #XXXX` in your comment to auto-close the issue that your PR fixes
(if such).

### CODE REVIEW

**Review by tomchop — APPROVED** [review]

**Comment by jaegeral** [comment]
Hey @cudeso could you check https://cla.developers.google.com/ if you can sign it, this is required for us to accept code.

Thx much

**Comment by cudeso** [comment]
> Hey @cudeso could you check https://cla.developers.google.com/ if you can sign it, this is required for us to accept code.
> 
> Thx much

The CLA has been submitted.

**Comment by jaegeral** [comment]
Checked CLA manually, CLA yes

**Review by jaegeral — APPROVED** [review]

**Comment by jaegeral** [comment]
Thx for the contribution

**Pull request closed without merging**
