### PR TITLE
fix error PR ref #1087

### PR DESCRIPTION
**Pull request by lprat**
fix error PR ref #1087

### CODE REVIEW

**Comment by kiddinn** [comment]
you'll need to sign the CLA and also update the branch, and then assign someone to review the change, in this case I would suggest johan

**Comment by berggren** [comment]
@lprat Can you sign the SLA so we can get this merged? Thanks!

**Comment by lprat** [comment]
@googlebot I fixed it.

**Comment by lprat** [comment]
Sorry, but i dont understand why bot not accept my sign of CLA...

**Comment by berggren** [comment]
Hi, this has been fixed in #1207 as part of a larger refactor and fixit for docker in TS. We now build base images automatically that is used.

Thanks @lprat for your help on this!

**Pull request closed without merging**
