### PR TITLE
Add button to remove Story

### PR DESCRIPTION
**Pull request by Henkan**
Add a button in the UI to remove a story.
The button is the same as the one used to remove a Timeline.

First time using Vue, so let me know if any change is required

### CODE REVIEW

**Comment by berggren** [comment]
Hi @Henkan thanks for adding this feature! I see that you include your build files in this PR. Can you run this:

```
docker exec -it $CONTAINER_ID yarn run --cwd=/usr/local/src/timesketch/timesketch/frontend build
```

If you are using the dev docker setup.

**Comment by berggren** [comment]
Hi @Henkan , did you have a chance to remove the build files? We recently did a large refactor of the API resources as well, so you might get some conflicts that need to be resolved. Let me know if you need any help.

**Comment by Henkan** [comment]
Hi,
Excuse me for the late answer. I didn't have the time to check yet and I'm not using the docker container. Is it alright if I remove the build files and only push the .vue files, once the conflicts have been resolved ?

**Comment by berggren** [comment]
> Hi @berggren ,
> Excuse me for the late answer. I didn't have the time to check yet and I'm not using the docker container. Is it alright if I remove the build files and only push the .vue files, once the conflicts have been resolved ?

Yes that is fine. I can rebuild the files after. Thanks!

**Comment by berggren** [comment]
@Henkan Let me know when you have chance to remove the build files and update the PR. After that we can get this merged.

**Comment by Henkan** [comment]
Hi @berggren,
I was busy with my exams so this took a long time, I'm sorry for that.
I have removed the build files to only keep the two .vue files. However, it seems that there are still conflicts with index.html and login.html and I'm not really sure why since I've deleted them as well in my repo. Do you have any idea on how to fix this ?

**Comment by berggren** [comment]
Hey @Henkan Sorry for the delay. The files are still there. I think the easiest solution is to just copy&paste the Vue code into another branch and create a new PR from that. The code looks fine, and we can merge from there.

**Comment by berggren** [comment]
@Henkan Friendly ping - can you take the vue code out, create a new PR? Let me know and we can get this merged.

**Comment by berggren** [comment]
@Henkan I'm closing this PR for now - reach out when you have a chance to update and create a new PR with only the vue file.

**Pull request closed without merging**
