### PR TITLE
Dockerized Timesketch enhancements

### PR DESCRIPTION
**Pull request by ilyaglow**
Solves #361 #330

Any feedback is appreciated

### CODE REVIEW

**Comment by ilyaglow** [comment]
Seems like commits are messed up a little after rebasing, hope it's okay.

**Comment by drewstinnett** [comment]
This branch works great for us, would love to see it get merged in

**Comment by witoff** [comment]
@ilyaglow this warning seems unnecessary to me, but can you confirm here that you're "okay with your commit being contributed to this project" so we can get you merged in?

**Comment by ilyaglow** [comment]
Okay with my commit being contributed to this project

**Comment by ilyaglow** [comment]
Looks like @berggren's accept is needed. 

Sorry for the confusion, I should have cherry picked my changes instead of rebasing commits after merging with the upstream.

**Comment by berggren** [comment]
Hi @ilyaglow can you rebase to current master to get a cleaner PR. I'll review after this is done. Thanks!

**Comment by ilyaglow** [comment]
Sure @berggren you mean merge with current master branch? Or you would like me to send another PR?

**Comment by berggren** [comment]
Hi @ilyaglow ! These changes has been fixed in other PRs, but please file a ticket if there is anything that is broken and we can start another PR. Thanks for contributing!

**Pull request closed without merging**
