### PR TITLE
Create search indices and timelines

### PR DESCRIPTION
**Pull request by berggren**
Fixes: #377 
Reviewer: @hiddenillusion

### CODE REVIEW

**Comment by hiddenillusion** [comment]
ack, will have a look

**Comment by hiddenillusion** [comment]
This still doesn't seem to be working as expected. If the `es_index_name` supplied to `create_searchindex()` already exists in ES, `create_searchindex()` still returns a status code **201** even though a _new_ SearchIndex wasn't created.

The most reliable way I've tested existence prior to attempting to create a new searchindex was iterating & comparing index_names from the data returned in `fetch_resource_data(u'searchindices/')`, but that may be slow depending on the number.

**Comment by berggren** [comment]
Hey, good point and I missed changing to the correct status code. I have made some small changes to make this a bit more intuitive.

The method is now named get_or_create_searchindex(), and it will return the searchindex object together with a boolean indicating if the index was created or if it already existed.

Example:
api_object.get_or_create_searchindex(es_index_name="123456", searchindex_name="foobar")
(<timesketch_api_client.client.SearchIndex at 0xdeadbeef>, False)

I was thinking of returning HTTP 409 (conflict) and raise an error if the index already existed, but I then this need to be handled in all client code, and I think that most people don't care. They just want the index object.

PTAL

**Comment by hiddenillusion** [comment]
[one](https://github.com/google/timesketch/pull/380/commits/673e4f8623de9f5d8725035927687897ec4bd1a4#diff-cfc277cad8b430c4868c66b63ef6ded2R197) minor change needs to be done then it LGTM:

`if response.status_code != HTTP_STATUS_CODE_20X` needs to be `if response.status_code not in HTTP_STATUS_CODE_20X` since `HTTP_STATUS_CODE_20X` is a list.

**Comment by berggren** [comment]
Done, thanks for the review @hiddenillusion !

**Pull request merged**
