### PR TITLE
add bs4 and mock to requirements.txt

### PR DESCRIPTION
**Pull request by jaegeral**
Adding both packages as they are used in multiple tests.

### CODE REVIEW

**Comment by berggren** [comment]
These test dependencies are already present in the test_requirements file:
https://github.com/google/timesketch/blob/master/test_requirements.txt

They are automatically installed in the dev and e2e containers.

**Review by berggren — CHANGES_REQUESTED** [review]
These test dependencies are already present in the test_requirements file:
https://github.com/google/timesketch/blob/master/test_requirements.txt

They are automatically installed in the dev and e2e containers.

**Comment by kiddinn** [comment]
yes. please revert this PR, since it is not needed, we don't need testing requirements to be added to the tools requirement file.

**Comment by jaegeral** [comment]
ACK closed

**Pull request closed without merging**
