### PR TITLE
Support more datetime formats for time filters

### LINKED ISSUE #2047: ValueError in date method in DateIntervalChip
**Describe the bug**
A date chip value in the following format ```"value": "YYYY-MM-DD -1d +1d" ``` raises a ValueError which is caught as expected, see below: 

https://github.com/google/timesketch/blob/5a0040531e979022c91017c2c641273dc1ec1183/api_client/python/timesketch_api_client/search.py#L163-L165

Because of this, views with this particular type of date format are being ignored/skipped when calling ```sketch.list_views()```.

### PR DESCRIPTION
**Pull request by sydp**
+ What existing problem does this PR solve? 
#2047 

+ What new feature is being introduced with this PR?
Ability to accept different non-standard date formats in DateIntervalChip()

+ Overview of changes to existing functions if required.

This PR updates DateIntervalChip() to now accept dates of the form:
* "2021-12-12T12:12:12"
* "2021-12-12 12:12:12"
* "2021-12-12"

**Checks**

- [ ] All tests succeed.
- [ ] Unit tests added.
- [ ] e2e tests added.
- [ ] Documentation updated.

**Closing issues**

closes #2047

### CODE REVIEW

**Review by berggren — APPROVED** [review]
LGTM

The eslint error in the tests in unrelated to this change. I'll investigate that seperatly.

**Comment by berggren** [comment]
Hey @sydp is this PR ready to merge? I LGTM it, but it is in draft? :)

Let me know.

**Comment by sydp** [comment]
> Hey @sydp is this PR ready to merge? I LGTM it, but it is in draft? :)
> 
> 
> 
> Let me know.

@berggren Thanks for reviewing.  I was planning to test one more thing before undrafting this, will let you know once I've done it (hopefully within the next day or two)

**Comment by hanej** [comment]
Any chance we can get milliseconds supported as well if Timesketch supports it?

**Comment by sydp** [comment]
> Any chance we can get milliseconds supported as well if Timesketch supports it?

I don't see why not.  This PR doesn't quite address that so I raised a new issue #2081 for you.

**Comment by sydp** [comment]
@berggren this is ready for another review/merge (added extra code for timestamps with sub-second values)

**Comment by sydp** [comment]
@berggren friendly bump to get this merged :)

**Comment by berggren** [comment]
> @berggren friendly bump to get this merged :)

LGTM, but there is a linter error (not related to this PR) that holds this up. I'm looking into it and will push a fix.
Will merge this as soon as that is fixed.

**Pull request merged**
